### ISSUE TITLE
The docs hosted on gh-pages should contain an image of a suitcase...possibly clipart. 

### ISSUE THREAD

**Issue by swstack** [digidotcom/python-suitcase#1]

**Comment by nateglims** [comment]
Maybe incorporate some sort of snake theme into the clipart.

**Comment by posborne** [comment]
That would be nice, as long as the license is good.  I really like the simple black-and-white sort of images that go with the pocoo projects.

* http://flask.pocoo.org/docs/0.10/
* http://click.pocoo.org/4/
* http://jinja.pocoo.org/docs/dev/
* http://werkzeug.pocoo.org/

**Comment by nateglims** [comment]
http://i.imgur.com/vLh1aZ6.gif?1

I made this for your project.

**Comment by swstack** [comment]
This task was partly only in jest...however I am envisioning a suitcase full of bytes/bits or something :P  And yes possibly a snake because why not.

**Comment by nateglims** [comment]
What does a bit look like?
