### ISSUE TITLE
Time for 0.8?

### ISSUE THREAD

**Issue by rtzoeller** [digidotcom/python-suitcase#14]
A substantial amount of new features and some bug-fixes have come in since the last 0.7 release. Are there any plans to release a Suitcase 0.8 in the near future?

**Comment by posborne** [comment]
I agree that it is about time for a 0.8.  I'll cut one.

**Comment by posborne** [comment]
Version 0.8 is now on PyPI: https://pypi.python.org/pypi/suitcase/.  Updated release notes: https://github.com/digidotcom/python-suitcase/blob/master/CHANGELOG.md
