### ISSUE TITLE
An updated version of Six is available.

### ISSUE THREAD

**Issue by rtzoeller** [digidotcom/python-suitcase#15]
More information can be found here https://mail.python.org/pipermail/python-announce-list/2015-October/010936.html

**Comment by posborne** [comment]
Since we do not freeze the version of six, I believe this should be pulled in automatically.  Is there an associated regression?

**Comment by posborne** [comment]
Confirmation that tests are passing with six 1.10.0: https://travis-ci.org/digidotcom/python-suitcase/jobs/83419436#L218
