### ISSUE TITLE
Broken `BitField`

### ISSUE THREAD

**Issue by peteut** [digidotcom/python-suitcase#17]
`BitField` is broken, it needs a metaclass in order to use `OrderedDict` instead of `dict` for `kwargs`. Otherwise the order of the fields is not guaranteed. 

Use [six.add_metaclass](https://pythonhosted.org/six/index.html?highlight=metaclass#six.add_metaclass) to add the metaclass. 

Here's a example of a metaclass which use `OrderedDict` from the Python Cookbook 3rd edition:

```python
# Metaclass that uses an OrderedDict for class body
class OrderedMeta(type):
    def __new__(cls, clsname, bases, clsdict):
        d = dict(clsdict)
        order = []
        for name, value in clsdict.items():
            if isinstance(value, Typed):
                value._name = name
                order.append(name)
        d['_order'] = order
        return type.__new__(cls, clsname, bases, d)

    @classmethod
    def __prepare__(cls, clsname, bases):
        return OrderedDict()
```

**Comment by peteut** [comment]
This issue is tackled w/ `_global_seqno` or so, this is *not* an issue.

**Comment by posborne** [comment]
Yes, the initial version of suitcase was written to support Python 2.4, so `OrderedDict` was not used.
