### ISSUE TITLE
LengthField inside BitField?

### ISSUE THREAD

**Issue by mikewadsten** [digidotcom/python-suitcase#18]
I'm looking at implementing a library for Bluegiga's BGAPI (a fairly simple serial API, not unlike XBee API) in Python using Suitcase, and I've hit a wrinkle that may need addressing.

You can see the format of each frame [here](https://github.com/jrowberg/bglib/blob/master/Python/bglib.py#L672). The payload length is encoded across **11** bits - the lowest 3 bits of the first byte, and the entire second byte.

My initial naive attempt is as follows:

```python
class BGAPIFrame(Structure):
    head = BitField(16,
        is_event=BitBool(),
        technology_type=BitNum(4),
        length=LengthField(BitNum(11)))  # 3 bits of byte 0, 8 bits of byte 1
    class_id = UBInt8()
    command_id = UBInt8()
    payload = Payload(head.length)
```

But this of course fails:
```
Traceback (most recent call last):
  File "bgapi.py", line 6, in <module>
    class BGAPIFrame(Structure):
  File "bgapi.py", line 13, in BGAPIFrame
    payload = Payload(head.length)
AttributeError: 'FieldPlaceholder' object has no attribute 'length'
```

I vaguely remember some Bluegiga documentation saying that even though the length is 11 bits, in real life no message will be nearly as long (I'll check in the morning when I get back to work), so maybe we'd get away with something like this:

```python
class BGAPIFrame(Structure):
    head = BitField(8,
        is_event=BitBool(),
        technology_type=BitNum(4),
        _length=BitNum(3))
    length = LengthField(UBInt8())
    class_id = UBInt8()
    command_id = UBInt8()
    payload = Payload(length)
```

But, you know, that isn't the actual frame definition.

Do you have any better suggestions of how to accomplish this?

**Comment by posborne** [comment]
Pesky Protocols!  I've thought threw a few approaches in my mind, but none of them seem to be quite functional.

It would of course be possible to define a custom field that implements the same interface as `LengthField` and make things work.  That being said, I think there is probably a reasonable change to `LengthField` that could be made that would allow for the `BitField` to be wrapped.

I'll take a quick stab to see if that idea has legs.

**Comment by posborne** [comment]
I have a partial approach implemented on a branch if you are interested.  Still needs some work and tests but feel free to evaluate it.

**Comment by mikewadsten** [comment]
If I copy the example you provided in that commit message, I get the same error as before, on class declaration.

```python
from suitcase.structure import Structure
from suitcase.fields import LengthField, BitField, BitBool, BitNum, UBInt8, Payload

def _set_length(field, length):
    field.length = length


class BGAPIFrame(Structure):
    head = LengthField(
            BitField(16,
                is_event=BitBool(),
                technology_type=BitNum(4),
                length=LengthField(BitNum(11))),
            get_length=lambda f: f.length,
            set_length=_set_length)
    class_id = UBInt8()
    command_id = UBInt8()
    payload = Payload(head.length)


def parse_frame(data):
    return BGAPIFrame.from_data(data)
```
```
Traceback (most recent call last):
  File "bgapi.py", line 9, in <module>
    class BGAPIFrame(Structure):
  File "bgapi.py", line 19, in BGAPIFrame
    payload = Payload(head.length)
AttributeError: 'FieldPlaceholder' object has no attribute 'length'
```

If I change `payload` so it's declared as `Payload(head)`, I don't get that AttributeError on load, but I do get one on `BitField` when I try to use it:

```
>>> f = parse_frame('\x00\x00\x00\x01')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bgapi.py", line 23, in parse_frame
    return BGAPIFrame.from_data(data)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 247, in from_data
    m.unpack(data)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 300, in unpack
    return self._packer.unpack(data, trailing)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 61, in unpack
    self.unpack_stream(stream)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 95, in unpack_stream
    length = field.bytes_required
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 664, in bytes_required
    return self.length_provider.get_adjusted_length()
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 483, in get_adjusted_length
    return self.getval() * self.multiplier
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 454, in getval
    length_value = self.get_length(self.length_field)
  File "bgapi.py", line 15, in <lambda>
    get_length=lambda f: f.length,
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 1332, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'BitField' object has no attribute 'length'
```

**Comment by posborne** [comment]
Remove LengthField from the length BitNum.


On November 5, 2015, at 9:19 AM, Mike Wadsten <notifications@github.com> wrote:


If I copy the example you provided in that commit message, I get the same error as before, on class declaration.

from suitcase.structure import Structure
from suitcase.fields import LengthField, BitField, BitBool, BitNum, UBInt8, Payload

def _set_length(field, length):
    field.length = length


class BGAPIFrame(Structure):
    head = LengthField(
            BitField(16,
                is_event=BitBool(),
                technology_type=BitNum(4),
                length=LengthField(BitNum(11))),
            get_length=lambda f: f.length,
            set_length=_set_length)
    class_id = UBInt8()
    command_id = UBInt8()
    payload = Payload(head.length)


def parse_frame(data):
    return BGAPIFrame.from_data(data)

Traceback (most recent call last):
  File "bgapi.py", line 9, in <module>
    class BGAPIFrame(Structure):
  File "bgapi.py", line 19, in BGAPIFrame
    payload = Payload(head.length)
AttributeError: 'FieldPlaceholder' object has no attribute 'length'


If I change payload so it's declared as Payload(head), I don't get that AttributeError on load, but I do get one on BitField when I try to use it:

>>> f = parse_frame('\x00\x00\x00\x01')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bgapi.py", line 23, in parse_frame
    return BGAPIFrame.from_data(data)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 247, in from_data
    m.unpack(data)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 300, in unpack
    return self._packer.unpack(data, trailing)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 61, in unpack
    self.unpack_stream(stream)
  File "/home/mike/work/playground/suitcase/suitcase/structure.py", line 95, in unpack_stream
    length = field.bytes_required
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 664, in bytes_required
    return self.length_provider.get_adjusted_length()
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 483, in get_adjusted_length
    return self.getval() * self.multiplier
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 454, in getval
    length_value = self.get_length(self.length_field)
  File "bgapi.py", line 15, in <lambda>
    get_length=lambda f: f.length,
  File "/home/mike/work/playground/suitcase/suitcase/fields.py", line 1332, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'BitField' object has no attribute 'length'


�

**Comment by mikewadsten** [comment]
That works! Except that now this happens:
```
>>> f= parse_frame('\x00\x02\x00\x00\x01\x02')
>>> f
BGAPIFrame (
  head=BitField(
    is_event=False,
    technology_type=0,
    length=2,
  ),
  class_id=0,
  command_id=0,
  payload='\x01\x02',
)
>>> f.head
2
>>> f.head.length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'length'
>>> f.head.is_event
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'is_event'
```

The `__repr__` is presenting the head field correctly, but it looks like `__getattribute__` is grabbing the length instead of the field it wraps.

**Comment by posborne** [comment]
Yeah.  I'm not too surprised.  Didn't get a chance to write tests yet and one existing test is falling.  If you are feeling ambitious you can add to the branch.  I'm at a conference today.


On November 5, 2015, at 10:16 AM, Mike Wadsten <notifications@github.com> wrote:


That works! Except that now this happens:

>>> f= parse_frame('\x00\x02\x00\x00\x01\x02')
>>> f
BGAPIFrame (
  head=BitField(
    is_event=False,
    technology_type=0,
    length=2,
  ),
  class_id=0,
  command_id=0,
  payload='\x01\x02',
)
>>> f.head
2
>>> f.head.length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'length'
>>> f.head.is_event
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'is_event'


The __repr__ is presenting the head field correctly, but it looks like __getattribute__ is grabbing the length instead of the field it wraps.

�

**Comment by posborne** [comment]
This is kinda unrelated, but I was reviewing things again and realized that you can do the following with a lambda to get rid of the separate function for setting the length:

```python
class BGAPIFrame(Structure):
    head = LengthField(
            BitField(16,
                is_event=BitBool(),
                technology_type=BitNum(4),
                length=LengthField(BitNum(11))),
            get_length=lambda f: f.length,
            set_length=labda f, l: setattr(f, 'length', l))
    class_id = UBInt8()
    command_id = UBInt8()
    payload = Payload(head.length)
```
