### ISSUE TITLE
Would dispatching solve this problem?

### ISSUE THREAD

**Issue by mikewadsten** [digidotcom/python-suitcase#20]
I think, given the [example in the API docs](http://digidotcom.github.io/python-suitcase/latest/api.html#suitcase.fields.DispatchField), that the `DispatchField` field might help us implement the BGAPI protocol (see #18 for a tiny bit more detail), but I'm looking for your opinion, @posborne.

Like I said in #18, a BGAPI protocol frame looks like this:
```python
class BGAPIFrame(Structure):
    head = LengthField(
            BitField(16,
                is_event=BitBool(),
                technology_type=BitNum(4),
                length=BitNum(11)),
            get_length=lambda f: f.length,
            set_length=_set_length)
    class_id = UBInt8()
    command_id = UBInt8()
    payload = Payload(head)
```

The thing is, the `payload` in this case varies by (class ID, command ID). For example, a GAP Discover command and response will look like this:

```python
class BGAPIHeader(Structure):
    head = LengthField(
            BitField(16,
                is_event=BitBool(),
                technology_type=BitNum(4),
                length=BitNum(11)),
            get_length=lambda f: f.length,
            set_length=_set_length)
    class_id = UBInt8()
    command_id = UBInt8()


class GAPDiscoverCommand(Structure):
    header = SubstructureField(BGAPIHeader)
    # Actual body here
    mode = UBInt8()

    def __init__(self):
        self.header.class_id = 6
        self.header.command_id = 2

class GAPDiscoverResponse(Structure):
    header = SubstructureField(BGAPIHeader)
    result = ULInt16()  # success if 0, error codes are non-zero
```

I structured it that way so that `GAPDiscoverCommand()` is correct and `GAPDiscoverResponse.from_data('\x00\x04\x06\x02\x00\x00\x00\x00')` will work.

I've tried a bunch of different ways to use (multiple) inheritance to contain a lot of the duplicated code (like putting `header = SubstructureField(BGAPIHeader)` in the parent class, etc.) but I'm not an expert on wrangling `super` usage.

It looks like I could do something like this instead. Do you agree?

```python
class Empty(Structure):
    pass

class GAPDiscoverResponse(Structure):
    result = ULInt16()

class BGAPIFrame(Structure):
    head = ...
    cls_cmd = DispatchField(UBInt16())  # So that '\x01\x02' turns into 0x0102
    body = DispatchTarget(dispatch_field=cls_cmd, dispatch_mapping={
        0x0602: GAPDiscoverResponse,
        # etc etc
    })

# BGAPI is little-endian all over. \x01\x00\x02\x00 -> 0x201
>>> BGAPIFrame.from_data('\x00\x04\x06\x02\x01\x00\x02\x00').body
GAPDiscoverResponse (
  result=0
)
```

We'll be auto-generating most of this Python code from an XML description of the API provided by Bluegiga, so don't worry too much about the human effort that will go into writing it like this. :)

**Comment by posborne** [comment]
Interesting discussion.  `DispatchField` is something I added (way back when) because I thought it would prove useful (and I still do) but which hasn't fit well with the system architectures used in systems utilizing pacman I have built.  Those systems have ended up with an architecture requireing dynamic dispatch with command handlers registering themselves at runtime rather than having a more static dispatch model.

I think what you have in the last example seems very reasonable and will allow you to both dispatch based on the `class_id`/`command_id` pair and automatically populate the value when buliding packets.

If you want to break them apart for debugging, you could do the following.  Unfortunately, I don't think setval would work as well (http://digidotcom.github.io/python-suitcase/latest/api.html#suitcase.fields.FieldProperty):

```python
class BGAPIFrame(Structure):
    head = ...
    cls_cmd = DispatchField(UBInt16())  # So that '\x01\x02' turns into 0x0102
    class_id = PropertyField(cls_cmd, lambda v: v & 0xFF00 >> 8),
    cmd_id = PropertyField(cls_cmd, lambda v: v & 0xFF),
    body = DispatchTarget(dispatch_field=cls_cmd, dispatch_mapping={
        0x0602: GAPDiscoverResponse,
        # etc etc
    })
```

Anyway, doesn't matter much for your use case.  Sounds like combining the fields should work out alright.

If things are not working out well, I think it is still very reasonable to have a little bit of code that handles the mapping between layers with the mapping table handled in data structures outside of `suitecase`.

Code generation for the win!

**Comment by mikewadsten** [comment]
219 lines of XML-parsing and code generation, and nearly 2400 generated lines, later, I can confirm that my last example does essentially work. I did need to pass `length_provider=head` to the `body` field though.

```python
# Hundreds of generated Structure subclasses, plus a pair of dispatch_mapping dicts
# ...

def _set_length(field, length):
    field.length = length


class BGAPIRequest(Structure):
    """BGAPI request frame structure."""
    head = LengthField(
            BitField(16,
                is_event=BitBool(),
                technology=BitNum(4),
                length=BitNum(11)),
            get_length=lambda f: f.length,
            set_length=_set_length)
    cls_cmd = DispatchField(UBInt16())  # We combine these into one number.
    body = DispatchTarget(length_provider=head,
                          dispatch_field=cls_cmd,
                          dispatch_mapping=_request_dispatch)


class BGAPIResponse(Structure):
    """BGAPI response frame structure."""
    head = LengthField(
            BitField(16,
                is_event=BitBool(),
                technology=BitNum(4),
                length=BitNum(11)),
            get_length=lambda f: f.length,
            set_length=_set_length)
    cls_cmd = DispatchField(UBInt16())  # We combine these into one number.
    body = DispatchTarget(length_provider=head,
                          dispatch_field=cls_cmd,
                          dispatch_mapping=_response_dispatch)
```

I also generate functions like the following, which make it incredibly easy to actually make the relevant request frames:

```python
def gap_set_mode(discover, connect):
    m = BGAPIRequest()
    body = _GapSetModeRequest()

    body.discover = discover
    body.connect = connect
    m.body = body
    m.head.length = len(body.pack())
    return m
```

The tricky thing about that is the `m.head.length = ...` bit, which is needed because `head.length` isn't tied to the size of body. Would that be a plausible enhancement?

**Comment by posborne** [comment]
Hmm, If things are working properly, I think `head.length` should automatically be tied to `len(body.pack())` by means of a combination of `set_length` (which is doing `head.length = length`) and https://github.com/digidotcom/python-suitcase/blob/master/suitcase/fields.py#L474.

If things are working like I think they should be, your assignment to `length` is actually being overwritten write before `pack()` executes on the field.  Does it not work with the logic you have in there removed (for an actual pack test)?

**Comment by mikewadsten** [comment]
I'll check if packing these frames does generate the correct output. I guess I just expected the length value to be automatically tied to `len(body.pack())` upon assignment (if just so printing/repring the object gives you the right value) but we could live with that not being the case.

**Comment by mikewadsten** [comment]
Thought I had replied to this. Yes, the `length` field is updated correctly by `pack()` (and the packed frame is generated correctly).

Another dispatch-related question: We found that dispatching to an empty Structure inside of a ConditionalField doesn't actually work. (Are you keeping up?) (I'm trying to do it this way so we can determine the type of a received message by doing `isinstance(m.body, WhateverBody)` as opposed to `m.cls_cmd == WHATEVER` - but maybe I should learn to stop worrying and love the bomb.)

Simplified example:

```python
class EmptyBody(Structure):
    pass

class NonEmptyBody(Structure):
    result = UBInt8()

_mapping = {
    0x00: EmptyBody,
    0x01: NonEmptyBody
}

class Frame(Structure):
    length = LengthField(UBInt8())
    cond = DispatchField(UBInt8())
    what = UBInt8()
    _body = ConditionalField(
                DispatchTarget(length_provider=length,
                               dispatch_field=what,
                               dispatch_mapping=_mapping),
                condition=lambda m: m.cond != 0)
    _body2 = ConditionalField(..., condition=lambda m: m.cond == 0)  # inverse of _body
    

# Actual result
>>> Frame.from_data('\x00\x01\x00')
Frame (
  length=0,
  cond=1,
  what=0,
  _body=None,
  _body2=<ConditionalField: not included>,
)

# Expected result
Frame (
  length=0,
  cond=1,
  what=0,
  _body=Empty (
),
  _body2=<ConditionalField: not included>,
)
```

Meanwhile, it works when you make it unconditional:
```python
class Frame(Structure):
    length = LengthField(UBInt8())
    what = UBInt8()
    body = DispatchTarget(length_provider=length,
                          dispatch_field=what,
                          dispatch_mapping=_mapping)

>>> Frame.from_data('\x00\x00')
Frame (
  length=0,
  what=0,
  body=Empty (
),
)
```

and also when Empty is a conditional SubstructureField:
```python
class Frame(Structure):
    length = LengthField(UBInt8())
    what = UBInt8()
    body = ConditionalField(SubstructureField(Empty),
                            condition=lambda m: m.what == 0)

>>> Frame.from_data('\x00\x00')
Frame (
  length=0,
  what=0,
  body=Empty (
),
)
```

A cursory look at the code for ConditionalField and DispatchTarget doesn't reveal anything suspicious. The fact that it does work when it's not a Conditional over DispatchTarget tells me there's some interference between the two.

Any tips?

**Comment by posborne** [comment]
This check is what is preventing `unpack()` from propagating past the ConditionalField.  This appears to be an optimization (so we don't need to call the condition function again) but maybe one that we do not really want.  I wrote much of this long, long ago.

**Comment by posborne** [comment]
If you can modify and test with the following change, I would probably accept a PR:

```python
    def unpack(self, data):
        # length of data will be determined by bytes_required output value
        # which is in turn determined by our condition evaluation
        if self.condition(self._parent):
            self.field.unpack(data)
```

I think that would probably make things work more sane for what you are trying to do.
