### ISSUE TITLE
Read payload until Stop byte is recognized

### ISSUE THREAD

**Issue by itavero** [digidotcom/python-suitcase#21]
I'm trying to use Python for a protocol that has a variable-sized payload.
The payload has a fixed Start and Stop byte, which are guaranteed not to be used within the payload itself.
How can I tell Suitcase to read the payload up to the Stop byte, but not any further?

**Comment by posborne** [comment]
Hi @itavero.

The answer to your question is both yes and no.  If you give suitcase a fixed payload, it will generally do a good job of doing what you want.  Take for instance the `BoxedGreedy` structure from the unittests (https://github.com/digidotcom/python-suitcase/blob/master/suitcase/test/test_fields.py#L443):

```python
class BoxedGreedy(Structure):
    sof = Magic(b'\xAA')
    a = LengthField(UBInt8())
    b = UBInt8()
    payload = Payload()
    c = UBInt16()
    d = VariableRawPayload(a)
    eof = Magic(b'\xbb')
```

If you are able to provide suitcase with a full frame, it will handle this as expected.  Unfortunately, if you are looking to use `StreamProtocolHandler`, it isn't quite smart enough to figure out that it needs to scan for a boxing magic token (it is smart enough to scan for start-of-frame magic).

I would recommend that you perform frame scanning outside of suitcase and then hand off that buffer to suitcase to break down the field after you have performed that basic breakdown.

I discussed implementing support for trailing magic parsing with a colleague but we believe it would get a bit hairy and for now we are not planning on adding it.  I would welcome a PR attempting this is you (or anyone else) is feeling ambitious.

Make sense?
