### ISSUE TITLE
Supporting attribute assignment in structure __init__

### ISSUE THREAD

**Issue by eisensheng** [digidotcom/python-suitcase#40]
I would like to use this issue to start a discussion on allowing structure attribute assignment through ``Structure.__init__`` parameters.

It's a nice feature to reduce lines of code without making it harder to grasp what's going on during structure initialization.  The nature of a field's ordering in a structure and its memory layout also allows for ``*args`` to be used.  Since Django also provides this kind of interface, I don't think it could be harmful.

Considering the following scenario:
```python
from suitcase import fields, structure


class SizedString(structure.Structure):
    size = fields.LengthField(fields.ULInt8())
    data = fields.Payload(size)


class Pair(structure.Structure):
    key = fields.SubstructureField(SizedString)
    value = fields.SubstructureField(SizedString)


class PackedDictionary(structure.Structure):
    pairs = fields.FieldArray(Pair)


def pack_pair(k, v):
    pair = Pair()

    pair.key = SizedString()
    pair.key.data = k.encode('utf-8')

    pair.value = SizedString()
    pair.value.data = v.encode('utf-8')

    return pair


def pack_dictionary(mapping):
    packed_dict = PackedDictionary()
    packed_dict.pairs = [pack_pair(*i) for i in mapping.items()]
    return packed_dict


print(pack_dictionary({'A': 'Latin Capital letter A',
                       'B': 'Latin Capital letter B'}).pack())
```

The same code could be written with attribute initialization through the ``__init__`` constructor as:
```python
from suitcase import fields, structure


class SizedString(structure.Structure):
    size = fields.LengthField(fields.ULInt8())
    data = fields.Payload(size)


class Pair(structure.Structure):
    key = fields.SubstructureField(SizedString)
    value = fields.SubstructureField(SizedString)


class PackedDictionary(structure.Structure):
    pairs = fields.FieldArray(Pair)


def pack_dictionary(mapping):
    return PackedDictionary([Pair(SizedString(data=k.encode('utf-8')),
                                  SizedString(data=v.encode('utf-8')))
                             for k, v in mapping.items()])

print(pack_dictionary({'A': 'Latin Capital letter A',
                       'B': 'Latin Capital letter B'}).pack())
```

So please let me know what you think.

**Comment by posborne** [comment]
Hi @eisensheng, thanks for creating the issue to discuss and sorry about the delay!

I'm quite amenable to the suggestion that we allow for passing arguments to init in order to reduce the number of lines required.  I think the way that this could most easily be supported would be via keyword arguments to the constructor matching the names of the fields.  E.g.

```python
class EchoProtocolFrame(Structure):
    frame_type = UBInt8()
    payload_length = LengthField(UBInt16())
    payload = Payload(payload_length)

echo = EchoProtocolFrame(
    frame_type=0x00,
    payload="Hello, world!",
)
```

Or, in your example:

```python
class SizedString(structure.Structure):
    size = fields.LengthField(fields.ULInt8())
    data = fields.Payload(size)


class Pair(structure.Structure):
    key = fields.SubstructureField(SizedString)
    value = fields.SubstructureField(SizedString)


class PackedDictionary(structure.Structure):
    pairs = fields.FieldArray(Pair)


def pack_dictionary(mapping):
    return PackedDictionary(pairs=[Pair(SizedString(data=k.encode('utf-8')),
                                        SizedString(data=v.encode('utf-8')))
                                   for k, v in mapping.items()])

print(pack_dictionary({'A': 'Latin Capital letter A',
                       'B': 'Latin Capital letter B'}).pack())
```

I find this form very easy to read (it is very similar to C's designated initializers for structs / Rust's struct initialization) and it removes the complications of dealing with order and potentially  needing to deal with reserved positional arguments that might be needed in the future.  It is a little annoying in the case of `PackedDictionary` but probably the right thing in the long run.

I had thought about adding this several times in the past but never got around to it?  Would you be interested in taking a crack at implementing?  Full disclosure, I am no longer working full-time on Python (I am not at Digi any longer), but I do have access again and plan to continue to act as maintainer.

**Comment by rtzoeller** [comment]
I have a quick implementation whipped up for this - I'll be writing some tests for it and hopefully have a pull request up later today.

@posborne to clarify, we only want to support keyword arguments and not positional ones, for forwards-compatibility reasons? If so, is there a typo in your `pack_dictionary` method in your test case? I feel that it should read as follows:

```python
def pack_dictionary(mapping):
    return PackedDictionary(pairs=[Pair(key=SizedString(data=k.encode('utf-8')),
                                        value=SizedString(data=v.encode('utf-8')))
                                   for k, v in mapping.items()])
```

**Comment by posborne** [comment]
> @posborne to clarify, we only want to support keyword arguments and not positional ones, for forwards-compatibility reasons? If so, is there a typo in your pack_dictionary method in your test case? I feel that it should read as follows:

Correct.  And you are right that my example was not accurate (in that it was still using a positional arg).  In general, I think the explicitness of keyword arguments is better and it deals with problems that would be created by having positional arguments in the position of fields where the value should not really be provided by the author (e.g. a length field).

**Comment by rtzoeller** [comment]
@posborne can this be closed?

**Comment by posborne** [comment]
Yep :)
