### ISSUE TITLE
__repr__ implementation missing for FieldProperty

### ISSUE THREAD

**Issue by eisensheng** [digidotcom/python-suitcase#5]
`None` will be printed instead of the string representation behind the `FieldProperty` value when the string representation of a `Structure` instance is printed on the terminal.

**Comment by posborne** [comment]
Thanks for filing the issue.

I can see two ways of fixing this:

1. Add a `__repr__` for FieldProperty
2. Modify the `__repr__` for BaseField to return `repr(self.getval())`

I think I'm leaning towards the second option as it is probably a better default than accessing `_value` which may not be used by many subclasses (this in itself is probably indicative of a slight design problem, e.g. violation of Liskov).

**Comment by eisensheng** [comment]
> I think I'm leaning towards the second option as it is probably a better default than accessing _value which may not be used by many subclasses (this in itself is probably indicative of a slight design problem, i.e. violation of Liskov).

Sounds good to me. The thing is I printed out the structure to toy around with it and see what the library parsed from the binary data. But the field always showed the `None` value on the string representation to me. I was wondering why and had a difficult time to figure it out.

The library is very nice though. Thanks for sharing the code!

**Comment by eisensheng** [comment]
Nice :+1:
