### ISSUE TITLE
length_provider to DispatchTarget can't be None

### ISSUE THREAD

**Issue by eisensheng** [digidotcom/python-suitcase#7]
The argument for the `length_provider` parameter in the DispatchTarget `__init__` method can't be `None`. 

The documentation for [`suitcase.fields.DependentField`](http://digidotcom.github.io/python-suitcase/0.6/api.html#suitcase.fields.DependentField) and [`suitcase.fields.DispatchField`](http://digidotcom.github.io/python-suitcase/0.6/api.html#suitcase.fields.DispatchField) suggests that it should be possible to pass `None` or even leave the argument out.

It would be desirable to have this functionality though to mix and parse sub-structures with a fixed length and without a length provider and sub-structures with a dynamic length given a length provider and extra payload.

**Comment by posborne** [comment]
For some context, I haven't actually found opportunity to use `DependentField` and `DispatchField` all that much in practice as of yet.  I wouldn't call them completely broken, but it is very likely that we can improve on what is present significantly.

**Comment by eisensheng** [comment]
Parsing Socks5 provides such an opportunity to encounter the need for this field. The protocol allows to specify an IPv4, IPv6 and a variable length DNS identifier. So these fields would come in handy to understand this protocol.

Time is a scarce thing. I'll look if I can improve on this situation. Maybe the logic of the `Payload` field can serve as an inspiration since it behaves the same way.

**Comment by eisensheng** [comment]
:+1:
